default_agent: research_agent_biomni_tools
agents:
  research_agent_biomni_tools:
    name: research_agent_biomni_tools
    entrypoint: /Users/hpoonawa/Documents/Gitlab/sample-best-practices-for-life-science-research-agents/labs/02-tools/01-database-tools-gateway/agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::942514891246:role/researchappStackInfra-RuntimeAgentCoreRole-Uxm3QzVownz4
      execution_role_auto_create: false
      account: '942514891246'
      region: us-west-2
      ecr_repository: 942514891246.dkr.ecr.us-west-2.amazonaws.com/bedrock-agentcore-research_agent_biomni_tools
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: null
      agent_arn: null
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-research_agent_biomni_tools-builder
      execution_role: arn:aws:iam::942514891246:role/AmazonBedrockAgentCoreSDKCodeBuild-us-west-2-32acfcc928
      source_bucket: bedrock-agentcore-codebuild-sources-942514891246-us-west-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
